version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  app:
    build: .
    command: /bin/sh -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./sample:/sample
    ports:
      - "3000:3000"
    links:
      - redis
